RocketChat/EmbeddedChat

README.md

NEW: Development documentation

---

src/index.js

- use `js-cookie` instead of an instance (RCInstance) to get the cookies so that if cookies are present then the user is assumed to be logged in using some source

FIX: when cookies are there assume user present

---

package.json
playground/package-lock.json

Before the EmbeddedChat only supports node with version ^17.0.2 which throws error when added to the project. Now the support of ^18 has been added
Fixes #52

Updated peer dependency for React.js

---

src/components/ChatBody/ChatBody.js

Messages does not display after we click back oprion from starred or pinned messages.
1. Click on pinned/starred messages at the chat header
2. Once the pinned/starred messages come, click on `Go Back`
3. All the messages should come successfully on clicking back
All the messages should display on clicking Go back.
Empty chat body
[screen-capture (1).webm](https://user-images.githubusercontent.com/42451210/213522801-36c805b7-ae27-49a7-9330-99e41ec2670a.webm)
Fix #93

Fix Message Display after clicking on Go Back from starred/pinned message 

---

src/components/ChatInput/ChatInput.js

Currently, only ctrl+enter adds a newline instead of rocket.chat in which both shift+enter and ctrl+enter add a newline. many users including me are used to the shift+enter way of adding new lines.

[IMPROVE] shift+enter adds a newline in chat input

---

src/lib/searchToMentionUser.js

Whenever we type @ in empty textArea and erase it the list of the user to be mentioned still remains there.
The mention box should not be active when the user type @ after the text without the space
Fixes # (issue)
#163 
https://user-images.githubusercontent.com/67755128/222644141-828aa4bb-620e-4b1d-87d6-559195af1359.mp4

fix:tagging user section not closing

---

src/components/ChatBody/ChatBody.js
src/lib/api.js
src/lib/cloneArray.js
src/store/messageStore.js

Currently, we are polling all the messages each time we receive the stream-notify-room message. I have made a few changes to use DDP and API calls together for efficient real-time functionality.
1. On the first load HTTP call is made to fetch messages.
2. A DDP subscription is made to receive new messages and updates about the messages.
3. Currently DDP is enabled for:
- Case 1: New messages are inserted into the message list
- Case 2: Updates on already loaded message
- Case 3: handling delete message event
Now, listening to new messages has been made a lot easier. To listen for messages. One needs to call `await RCInstance.connect()` then one can add as many listeners as he sees fit by using `RCInstance.addMessageListener(callback);`
For example:
```
useEffect(() => {
if …
```

[NEW] Using ddp to get messages.

---

README.md

[FIX] Contributor Widget Not Updating

---

.gitignore
packages/react/src/components/Message/MessageDivider.js
packages/react/src/components/Message/MessageReactions.js
packages/react/src/components/Message/index.js
packages/react/src/components/SearchMessage/SearchMessage.js

Reverts RocketChat/EmbeddedChat#277
Changes broke the search message feature.

Revert "Feat/#274 replace message components with custom components"

---

packages/react/src/components/Markdown/Markdown.js
packages/react/src/components/RoomMembers/RoomMemberItem.js

This PR fixes minor linting errors that arose due to recent pr merges. In future, we should move to automatic testing and fixing of lint issues.

chor: lint fixes

---

README.md
packages/react/src/index.js
packages/react/src/stories/EmbeddedChat.stories.js
packages/react/src/stories/EmbeddedChatAuthToken.stories.js
packages/react/src/stories/EmbeddedChatTheme.stories.js
packages/react/src/stories/EmbeddedChatWithoutHeader.stories.js

Fixes #265
In the screenshot using the host as 4000

Fix/#265 added RC_HOST as env variable

---

packages/react/src/components/Message/MessageToolbox.js

Provided a simple fix by changing the z index of the message toolbox.
Behavior after changes:
https://github.com/RocketChat/EmbeddedChat/assets/98230836/ee30b1da-4ecd-4130-b448-b3bd86011c58

Fixed unexpected appearance of the message toolbox.

---

packages/react/src/components/ChatInput/ChatInput.js

Markdown shortcuts for bold and italic
The user can now style the font to bold and italic by using ctrl+b and ctrl+i shortcuts respectively.
Behavior:
Once the user presses any of the above mentioned shortcut keys after selecting some text, the text will be wrapped around "* *" or "_ _" to ensure that the text gets styled accordingly when the message is actually sent.
If the shortcut keys are pressed while no text is selected, the symbols will still appear but with the cursor between them.
The video below depicts the actual behavior:
https://github.com/RocketChat/EmbeddedChat/assets/98230836/86b34b9f-323d-43fe-955a-1df347edf8d0

Added markdown shortcuts for bold and italic font style (ctrl+b,ctrl+i)

---

packages/api/package.json
packages/react/package.json
packages/react/src/components/uiKit/blocks/PreviewBlock.js
packages/react/src/components/uiKit/elements/MultiStaticSelectElement.js
packages/react/src/components/uiKit/elements/OverflowElement.js
packages/react/src/components/uiKit/elements/StaticSelectElement.js
packages/react/src/components/uiKit/surfaces/BannerSurface.js
packages/react/src/components/uiKit/surfaces/FuselageSurfaceRenderer.js
packages/react/src/components/uiKit/surfaces/MessageSurface.js
packages/react/src/components/uiKit/surfaces/ModalSurface.js
yarn.lock

This PR removes unused project dependencies 
It also removes the fuselage completely. There are still a few components that need to be built and tested carefully:
1. OverflowElement
2. MultiStaticSelectElement
3. PreviewBlock
4. StaticSelectElement
The bundle size is now reduced to half of the earlier size.

Remove unused packages and fuselage

---

packages/rc-app/EmbeddedChatApp.ts
packages/rc-app/app.json
packages/rc-app/endpoints/CallbackEndpoint.ts
packages/rc-app/lib/getCallbackContent.ts
packages/rc-app/lib/getCallbackUrl.ts
packages/rc-app/lib/getTokenUrl.ts
packages/rc-app/lib/isAllowedOrigin.ts
packages/rc-app/settings/settings.ts

This commit introduces OAuth callback functionality to the EmbeddedChat application within RocketChat. It effectively integrates essential OAuth components, including client ID, client secret, and redirect URI handling, ensuring seamless authentication and authorization processes. By leveraging environment settings and callbacks, the update enhances the app's ability to connect securely with OAuth providers, thereby improving user authentication flow and overall application security. This addition marks a significant step in bolstering the app's connectivity and user experience, aligning with modern authentication standards.

added: oauth callbacks to RC app

---

packages/api/src/EmbeddedChatApi.ts
packages/auth/src/RocketChatAuth.ts
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/components/Message/Message.js
packages/react/src/index.js
packages/react/src/stories/EmbeddedChatAuthToken.stories.js
packages/react/src/stories/EmbeddedChatWithOAuth.stories.js
packages/react/src/stories/EmbeddedChatWithoutHeader.stories.js

This PR introduces the integration of RocketChat OAuth for user authentication, leveraging the third-party login feature. It provides a streamlined OAuth login flow, enhancing the user authentication process.
To enable RocketChat OAuth login, the following steps are necessary:
1. **Create a Third-Party Login (OAuth App)**: Set up an OAuth application to initiate the authentication process.
2. **Set Up Custom OAuth**: Configure custom OAuth in RocketChat to facilitate login using the created OAuth app.
3. **Install and Configure EmbeddedChatApp**: The EmbeddedChatApp must be installed and properly configured on the RocketChat server.
4. **Pass Authentication Props**: To activate this login method, pass the `auth={flow: 'OAUTH'}` props within the application.
- Manual testing was performed …

added login with rocketchat oauth

---

packages/react/src/components/Message/MessageToolbox.js

Fixed toolbox position which was affecting the readability of long messages
Closes #375 
Before:
After:

Fixed messageToolbox position

---

packages/api/rollup.config.js
packages/auth/rollup.config.js

Resolved build problem in windows environment by modifying the rollup configuration file to use a platform-independent external parameter.
- [✓] Identified the problem by debugging through the log file and confirmed it by replicating the issue in a dummy project with the same configuration.
- [✓] Updated the external parameter passed via the bundle function in the rollup configuration file, making it platform-independent. 
- [✓] Referred to the issue link for details for the fix: https://github.com/rollup/rollup/issues/3811
- [✓] Performed comprehensive testing on both Windows and Linux environments to ensure that it functions correctly.
Fixes #405 
Verification of the build process on Linux:
https://github.com/RocketChat/EmbeddedChat/assets/78961432/717b61d1-2f2b-43f9-91fb-b8faa275dbd8 …

fix: windows build issue, changed to platform independent external parameter in rollup config file

---

packages/react/src/components/Message/Message.js

Resolved warnings 5 and 6
Addresses #361

Warnings 5,6 Resolved

---

packages/react/src/components/GenericModal/GenericModal.js
packages/react/src/components/Message/MessageToolbox.js
packages/react/src/components/Modal/Modal.js
packages/react/src/components/Modal/ModalBackdrop.js
packages/react/src/components/ReportMessage/ReportWindowButtons.js
packages/react/src/components/uiKit/blocks/ModalBlock.js

Feature to close the popup by pressing the Esc key or clicking on the overlay.
- [✓] Propagated the onClose function to the Modal backdrop via props to manage closure upon overlay click.
- [✓] Introduced a ref to ModalBackdrop for future comparison of the click location within the window.
- [✓] Implemented a handleEscape function and attached a window event listener to facilitate modal closure upon pressing the Esc key
- [✓] Managed the interaction between props, refs, and optimized with useCallback and useEffect, including a dependencies array to avoid unnecessary re-renders.
Fixes #402 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/16a631e6-b1f6-4bb1-895c-1d0272c07066

feat: Close modal on backdrop/overlay click or on Esc keydown

---

packages/react/src/components/AllThreads/AllThreads.js
packages/react/src/components/AllThreads/AllThreads.module.css
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/Menu/Menu.stories.js
packages/react/src/components/Message/MessageHeader.js
packages/react/src/components/Message/MessageMetrics.js
packages/react/src/components/MessageList/MessageList.js
packages/react/src/store/index.js
packages/react/src/store/threadsMessageStore.js

Added a new section "Threads menu" where users can navigate through ongoing threads in the channel, search for different messages, and navigate directly to those threads.
Fixes #441 
The following video demonstrates how it works:
https://github.com/RocketChat/EmbeddedChat/assets/78961432/9ef0a24f-46e0-4089-9cb5-457e5ff89f05
The following screenshot shows that the avatar will be displayed only when enabled:

feat: Added a Threads menu to easily access ongoing threads in a channel.

---

packages/react/src/components/EmbeddedChat.js

Resolved Channel Information Fetch Issue on Refresh
Fixes #424 
Fixes #340 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/a57e544e-a00d-441b-9f5b-89a2c95920d9

fix: Channel info fetch issue on refresh

---

packages/react/src/components/ChatHeader/ChatHeader.js

Added a feature to show an error message and log the user out when the channel doesn't exist. The same has been added whenever the `channelInfo` function is called when any one of these dependencies changes: `[isUserAuthenticated, RCInstance, setChannelInfo]`
Fixes #418 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/914a6740-535d-497d-9039-883b14f5babd

feat: added feature to show error message and log user out when channel doesn't exist

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/store/channelStore.js

Resolved issue with fetching messages, member, channel info and roles in private channels.
Fixes #423 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/abf8409d-f228-4ad2-90c3-1250869dbd64
Note: In the video, zishan.barun@gmail.com is the authorized user and ahmadzishan7277@gmail.com is the unauthorized user. This is to demonstrate the functionality of the app.

fix: Addressed issues related to fetching different informations in private channels.

---

packages/react/src/components/AllThreads/AllThreads.js
packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/DynamicHeader/DynamicHeader.js
packages/react/src/components/EmbeddedChat.js
packages/react/src/components/MessageList/MessageList.js
packages/react/src/hooks/useFetchChatData.js

**Previously, when going back, the `handleGoBack` function, which calls `getMessagesAndRoles` to set all messages back in the state, could be directly passed as a prop from `ChatBody` to `MessageList` since it was the child component of it. However, now the `handleGoBack` function has to be implemented in `ChatHeader`, which is not a child of `ChatBody` and the `handleGoBack` button uses the function `getMessagesAndRoles`, which was defined inside `ChatBody`. So the same function has to be reused here as well. Hence, In order to avoid code duplication, a custom hook is introduced for reusability.**
Note: Since a new custom hook is introduced to avoid code duplication, please review the CustomHook section of the PR carefully to check for any potential state problems. I have tested it, and …

fix: Back Button Inconsistency in Threads and Starred/Pinned Sections.

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/store/userStore.js

Fixed the issue where, in read-only channels, users with posting permissions can now send messages as usual. However, those users without permission to post can still read messages but are restricted from sending messages to the group. They will be notified that the group is read-only, ensuring appropriate behavior.
Fixes #420 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/7582dc84-f976-4442-aad3-c9937945a72c
Note: This PR changes the backend code and requires a rebuild.

fix: fixed the app's behavior in read-only channels.

---

packages/react/src/components/ChatInput/ChatInput.js

Fixes #384 
https://github.com/RocketChat/EmbeddedChat/assets/93793691/2f83b544-e5b7-465e-9163-729f49d3e3c8

Handle 'Message Too Long"

---

packages/react/src/components/Message/Message.js
packages/react/src/components/SearchMessage/SearchMessage.js
packages/react/src/components/SearchMessage/SearchMessage.module.css

Make search tab consistent with threads & RC

---

packages/react/src/components/SearchMessage/SearchMessage.js

I have observed some minor bugs introduced by PR #497 , and this PR is intended to address these issues of infinite renders and console errors as quickly as possible
Fixes #502
https://github.com/RocketChat/EmbeddedChat/assets/78961432/9430f9e8-cc01-4396-8f12-90bd17e51e2b

fix: infinite render and console errors due to search component

---

packages/react/src/components/MessageList/MessageList.js

Added no pinned messages and no starred messages text in the message list component.

---

packages/react/src/components/Menu/Menu.js

Fixes #522 
https://github.com/RocketChat/EmbeddedChat/assets/93793691/90257887-04f3-471a-b911-3040439b7e84

[Chore] Handle menu toggle event

---

packages/react/src/components/PinnedMessages/PinnedMessages.js
packages/react/src/components/StarredMessages/StarredMessages.js

[FIX] Starred & Pinned messages sidebars fetch APIs infinitely

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/store/settingsStore.js

This pull request is intended to fix the static message limit set in the code.
Fixes #527 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/ca8898ee-1770-40ea-9827-9cbdd4854a1b
Note : This requires a rebuild of EC as there are some backend codes introduced.

fix: fixed static message limit to adapt to workspace setting

---

packages/react/src/components/Attachments/ImageGallery.js
packages/react/src/components/Attachments/ImageGallery.module.css
packages/react/src/components/EmbeddedChat.js
packages/react/src/stories/EmbeddedChat.stories.js
packages/react/src/stories/EmbeddedChatAuthToken.stories.js
packages/react/src/stories/EmbeddedChatTheme.stories.js
packages/react/src/stories/EmbeddedChatWithOAuth.stories.js
packages/react/src/stories/EmbeddedChatWithoutHeader.stories.js

Aligned the throbber in the image gallery and fixed infinite loading even when image fetching fails in the newly added image gallery (The same is implemented in RC as well)
Separately, in relation to another issue: `isClosable` is set to true in story examples, causing confusion. It should only be enabled when the true prop is explicitly passed along with a proper `setClosable` function, rather than just a boolean value (which was causing errors in the console). To avoid confusion, I have set `setClosable` as false by default and am passing an empty function.
Fixes N.A
https://github.com/RocketChat/EmbeddedChat/assets/78961432/1e11cd83-5b6b-4a6a-baff-115f725b8e93
https://github.com/RocketChat/EmbeddedChat/assets/78961432/54e605e7-3395-4c42-9878-467b2b8b75fa

fix: centered throbber, added fallback, set default closable false

---

packages/react/src/components/AllThreads/AllThreads.js

This PR addresses the issue where the `No Threads Found` message is not displayed in the thread sidebar when there are no threads in the chat. The solution ensures that the message, along with an icon, is shown to indicate the absence of threads, improving the user experience by providing clear feedback.
https://github.com/RocketChat/EmbeddedChat/assets/123318221/ffe2a14b-fb1d-4ac2-a725-e2c40fd07068
Fixes : #529

[Feat] Display 'No Threads Found' Message in Thread Sidebar When No Threads Exist

---

packages/react/src/components/ChatBody/ChatBody.js

Just added a simple fix which checks the message object and only triggers the popup if a new message is received from any other user.
https://github.com/RocketChat/EmbeddedChat/assets/98230836/16d5999e-3f16-4a28-b110-cd57039aef66
Fixes #544

Fixed the unexpected appearance of the new messages notification on pinning and starring messages

---

packages/react-native/src/views/ChatRoomView/ChatRoomView.js
packages/react/src/components/EmbeddedChat.js
packages/react/src/hooks/useFetchChatData.js
packages/react/src/store/channelStore.js
packages/react/src/store/memberStore.js

Channel Members' Roles will now fetch from ChannelStore instead of UserStore.
Checkout #517 for the complete details about this fix.
Fixes #517

[Fix] Channel Members' Roles fetching from ChannelStore instead of UserStore

---

packages/react/src/components/Attachments/AttachmentMetadata.js
packages/react/src/components/Attachments/AudioAttachment.js
packages/react/src/components/Attachments/ImageAttachment.js
packages/react/src/components/Attachments/VideoAttachment.js

- Download button directly downloads the file
- Support QuickTime video types in safari (common, e.g. storybook)
- Download original file (if available) and default to preview file
Closes #547

fix: attachment direct download and video type support

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/components/EmbeddedChat.js
packages/react/src/components/Message/MessageHeader.js
packages/react/src/hooks/useFetchChatData.js
packages/react/src/store/memberStore.js
packages/react/src/store/userStore.js

This PR properly completes the showRoles functionality in Embedded Chat. The showRoles option has been available for a long time, but it hasn't been implemented in the code and has been pending for quite some time. This work aims to fully add that feature.
Fixes #564
https://github.com/RocketChat/EmbeddedChat/assets/78961432/b218f02a-2ee0-4443-9743-9d015743c999
Note : This PR requires a rebuild to incorporate a newly added API call

feat: user role display functionality

---

packages/react/src/views/ChatBody/ChatBody.js

- Due to close statement in ChatBody.js the websocket connection gets disconnected when the page refresh or it runs in new tab

Fixed unwanted close call in ChatBody.js

---

packages/react/src/views/ChatHeader/ChatHeader.js
packages/react/src/views/ReportMessage/MessageReportWindow.js

This pr demonstrates the visibility of thread title when initialsed by files and the message is visible in the report modal in thread
Fixes #625
https://github.com/user-attachments/assets/4335cccc-8d52-43c5-803f-83c00bda03cb

Fix thread title for files and  messages in report modal

---

packages/react/src/views/AttachmentHandler/Attachment.js
packages/react/src/views/AttachmentHandler/AudioAttachment.js
packages/react/src/views/AttachmentHandler/ImageAttachment.js
packages/react/src/views/AttachmentHandler/TextAttachment.js
packages/react/src/views/AttachmentHandler/VideoAttachment.js
packages/react/src/views/Message/BubbleVariant/Bubble.styles.js
packages/react/src/views/QuoteMessage/QuoteMessage.js

Fixes #563 
[Screencast from 2024-07-14 16-41-33.webm](https://github.com/user-attachments/assets/3dabb53c-69d1-40fe-8690-e7674badd872)

Fixed UI Inconsistencies while quoting messages

---

packages/react/src/hooks/useSetMessageList.js
packages/react/src/views/MessageAggregators/StarredMessages.js
packages/react/src/views/MessageAggregators/common/MessageAggregator.js

While opening starred messages, useSetMessageList hook was getting re-rendered many infinitely.
Fixes #642 
Previously:
https://github.com/user-attachments/assets/a7bdd883-4e8d-4688-a5ed-a2c0c1a7ff16
Now:
https://github.com/user-attachments/assets/d7f89547-772f-48a6-a303-86a49764c2e6
Added memoization to stop the infinite re-render cycle.
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-<pr_number> after approval.

[fix] Re-rendering fixed while opening pinned and starred messages.

---

packages/react/src/views/ReportMessage/MessageReportWindow.js

In report message, text shown is appropiate and readable.
Fixes  #610
https://github.com/user-attachments/assets/de1bab68-3f3b-4466-9587-26c90865322f

fixed  markdown rendering in report message

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/views/LoginForm/LoginForm.js

Trim Whitespaces in Username/Email Fields in EmbeddedChat Login Form
Fixes #656 
https://github.com/user-attachments/assets/5303abd9-294c-4b1f-a697-5d0b8841eaba
I did not trim for passwords because while registering on rocket chat , they allow having whitespaces after some `password` has been written
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-<pr_number> after approval.

Trim Whitespaces in Username/Email Fields in EmbeddedChat Login Form

---

packages/react/src/views/ChatInput/ChatInput.js
packages/react/src/views/ChatInput/ChatInputFormattingToolbar.js

Fix emoji display format and enable send icon on emoji selection
Fixes #662
https://github.com/user-attachments/assets/6647b85a-8e6e-4391-9cea-f0692a92332a
**Note**: The PR will be ready for live testing at [https://rocketchat.github.io/EmbeddedChat/pulls/pr-663](https://rocketchat.github.io/EmbeddedChat/pulls/pr-663) after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Display emoji in visual format and enable send icon on emoji selection

---

packages/react/src/views/ChatHeader/ChatHeader.js

Fix immediate UI update on logout by clearing messages and user avatar
Fixes #665 
[logout-issue-fix.webm](https://github.com/user-attachments/assets/088ab827-0775-4e8e-987c-8f9b29dcd48f)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-666
after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix logout issue

---

packages/react/src/views/MessageAggregators/SearchMessages.js

Memoized `debouncedSearch` with `useCallback` to prevent re-creation on each render
Fixes #650 
https://github.com/user-attachments/assets/5383b878-7e16-4225-b8a8-fb8411181057
Continuous API calls have been fixed 
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-<pr_number> after approval.

Fix: Prevent repeated API calls in searchMessages after typing stops

---

packages/ui-elements/tools/icons-generator.js

Fixes [https://github.com/RocketChat/EmbeddedChat/security/code-scanning/13](https://github.com/RocketChat/EmbeddedChat/security/code-scanning/13)
To fix the problem, we need to ensure that all occurrences of the '>' character in the `openingTag` string are replaced with ' {...props}>'. This can be achieved by using a regular expression with the global flag (`g`). This way, every instance of '>' in the `openingTag` string will be replaced, ensuring complete and correct modification of the SVG tag.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 13: Incomplete string escaping or encoding

---

packages/react/src/hooks/useRCAuth.js
packages/react/src/store/userStore.js
packages/react/src/views/Message/Message.js
packages/react/src/views/Message/MessageToolbox.js

Fixes #672 
Case 1:  When non-priviledged users are granted permission to pin/unpin messages
https://github.com/user-attachments/assets/9ed97726-bde6-4bc2-9686-3f2193bddd2d
Case 2: When non-priviledged users are not granted permission to pin/unpin messages
https://github.com/user-attachments/assets/aeb0f199-77da-4aa0-ba9b-56e91ed4262c
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-674 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix:  Restrict Pin Icon Visibility Based on User Permissions

---

packages/react/src/views/ChatBody/ChatBody.styles.js
packages/react/src/views/ChatInput/ChatInput.styles.js
packages/react/src/views/ChatLayout/ChatLayout.styles.js

Made message box responsive and fixed alignment
Fixes # (issue)
#616 , #629 
[message-box.webm](https://github.com/user-attachments/assets/cf6c175c-fdd1-4542-9d48-b90e40b895da)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-664 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Made message box responsive and fixed alignment

---

packages/react/src/hooks/useFetchChatData.js
packages/react/src/store/starredMessageStore.js
packages/react/src/views/ChatBody/ChatBody.js
packages/react/src/views/ChatHeader/ChatHeader.js
packages/react/src/views/ChatLayout/ChatLayout.js
packages/react/src/views/Message/Message.js
packages/react/src/views/MessageAggregators/StarredMessages.js
packages/react/src/views/MessageAggregators/common/MessageAggregator.js

Make thread starred messages appear in the sidebar.
Fixes #668
https://github.com/user-attachments/assets/a1e5642d-b4b5-425e-adfa-07c90203af9b
Realtime updation
https://github.com/user-attachments/assets/0c493e2a-2691-42b3-a2f1-ef760ee5b324
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-669 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Sidebar starred messages fetched by api to include thread messages.

---

packages/react/src/views/EmbeddedChat.js

Fix: Pin Permission Changes Not Reflected Without User Logout
Fixes #679 
https://github.com/user-attachments/assets/6bde2e5c-06ae-4cfd-8974-d58fbcdb2b1e
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-688 after approval. Contributors are requested to replace `<pr-number>` with the actual PR number.

fix: ensure pin permission changes reflect without requiring user logout

---

packages/react/src/hooks/useRCAuth.js
packages/react/src/store/messageStore.js
packages/react/src/views/EmbeddedChat.js
packages/react/src/views/Message/Message.js
packages/react/src/views/Message/MessageToolbox.js

Fix: Edit Message Permissions Not Reflecting Properly in EmbeddedChat
Fixes #701 
https://github.com/user-attachments/assets/d1bdb805-a9a0-4019-8bb6-9e488c2b761d
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-702 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix(permissions): ensure admin-granted edit message permissions apply in EmbeddedChat

---

.github/workflows/build-pr.yml
.github/workflows/deploy-pr.yml

This Pull request adds an additional pr approval check in `deploy-pr.yml` workflow. This adds validation to ensure the deploy-pr workflow runs only after PRs are approved by collaborators or owners. The GitHub API is used to verify approval status, preventing unauthorized deployments from forked repositories.
N/A

Added a validation check for pr approval in the deploy-pr workflow

---

packages/react/src/hooks/useFetchChatData.js
packages/react/src/store/userStore.js
packages/react/src/views/UserInformation/UserInformation.js

Fix User Info Modal Issues and Permission Handling
Fixes #755 
https://github.com/user-attachments/assets/f871934b-a8b3-4efc-b375-a74ef545c62c
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-756 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix: display bio, nickname, and statusText in User Info modal; resolve permission issues for viewing full user info

---

packages/react/src/views/Message/Message.js
packages/react/src/views/Message/MessageToolbox.js

Updated handleEditMessage functionality, and added validation for audio, video, and file message
When a user sends an audio/video/file message in the chat and clicks on the "Edit" option, they can record another audio or video/upload new file. However, the User should not be able to edit audio or video, or file messages. Instead, they can delete the message and send a new one
Fixes #696
Fixes #698
and
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-697 after approval.

Fix: Editing of Audio, Video and File Message

---

packages/api/src/EmbeddedChatApi.ts

Fixed image rendering issue in gallery
Fixes #758 
[Screencast from 2024-12-30 22-36-56.webm](https://github.com/user-attachments/assets/acb3051c-d9db-4508-b9c6-736566ec1c86)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-759 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix: image gallery showing error

---

packages/react/src/views/EmbeddedChat.js
packages/react/src/views/Message/Message.js
packages/react/src/views/Message/MessageHeader.js

This update ensures that user action messages are displayed when the room's topic, announcement, or description is updated. Additionally, it introduces styling changes for better alignment and includes a showUsername prop in Storybook for testing.
Fixes #745 
[Screencast from 2024-12-28 13-45-07.webm](https://github.com/user-attachments/assets/de869ca4-eba7-4b84-92bc-7e7fc14d8772)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-746 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix: user action messages

---

packages/react/src/views/ChatLayout/ChatLayout.js

Add user role display feature in EmbeddedChat messages
Fixes #737 
https://github.com/user-attachments/assets/bb55f6cb-95b4-49e1-b384-9761fc932b31
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-738 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Display user roles (Admin, Leader, Moderator, Owner) next to message headers

---

packages/api/playground/index.html
packages/api/playground/playground.js
packages/react/src/views/EmbeddedChat.js

Add Password Visibility Toggle Feature
Fixes #705 
https://github.com/user-attachments/assets/f74c36d3-cb86-4517-9b2d-0cd8550fae35
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-706 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

feat: add password visibility toggle feature in API development portal

---

packages/layout_editor/src/store/chatInputItemsStore.js
packages/layout_editor/src/views/ChatInput/ChatInputToolbar.jsx
packages/layout_editor/src/views/ThemeLab/LayoutSetting.jsx
packages/react/src/views/ChatInput/ChatInput.styles.js
packages/react/src/views/ChatInput/ChatInputFormattingToolbar.js
packages/react/src/views/ChatInput/InsertLinkToolBox.js
packages/react/src/views/EmojiPicker/EmojiPicker.js

Add 'Link' option in the ChatInput Box
Fixes #678 
https://github.com/user-attachments/assets/be7e568a-d847-494c-bda2-9789f1557bcc

feat: insert links in chat

---

packages/react/src/views/Message/MessageHeader.js

Fixes #797
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-798 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Capitalize the First Letter of User Roles in the UI

---

packages/react/src/views/MessageAggregators/common/MessageAggregator.js

Fix Display user roles in MessageAggregator when showRoles is true
Fixes #789
https://github.com/user-attachments/assets/f5cc80cb-2f32-4372-aa0d-e7429522c9e1
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-790 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix Display user roles in MessageAggregator when showRoles is true

---

packages/react/src/views/Message/Message.js
packages/react/src/views/Message/Message.styles.js

Disable the hover effect for User Action Messages
Fixes #794
https://github.com/user-attachments/assets/9fdb099d-7b35-4830-82a3-1eaf78a735cd
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-795 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Disable hover effect for User Action Messages

---

packages/react/src/views/Message/Message.js

The 'Copy' option functionality is now working for File messages
Fixes #715
https://github.com/user-attachments/assets/50711826-e0bd-4c9f-9975-cd42bd004e40
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-716 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: The 'Copy' option functionality is now working for File messages

---

packages/react/src/views/Message/MessageToolbox.js

-Implemented the "Pin Message" option in the "Reply in Thread" modal.
- Ensured the pinned message functionality integrates seamlessly with the existing pinning mechanism in the main chat.
Fixes #703 
https://github.com/user-attachments/assets/65c9a1f1-b486-4641-82f1-385b5d21054c

Add "Pin Message" Option in Reply-in-Thread Modal

---

packages/react/src/views/ChatInput/AudioMessageRecorder.js
packages/react/src/views/ChatInput/VideoMessageRecoder.js

Feat: Add Window for Adding Description to Audio & Video Messages
Fixes #769
https://github.com/user-attachments/assets/0c49f0b5-0293-4eeb-82e5-f01b3cef0f3a
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-770 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Feat: Added Window for Adding Description to Audio & Video Messages

---

packages/react/src/views/ChatInput/AudioMessageRecorder.js
packages/react/src/views/ChatInput/ChatInputFormattingToolbar.js
packages/react/src/views/ChatInput/VideoMessageRecoder.js

Fix: Disabled buttons both visually and functionally. 
Fixes #735
https://github.com/user-attachments/assets/f4dc55e1-c882-4e5a-8ba1-9785e1208a46
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-735 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Disabled buttons both visually and functionally

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/hooks/useFetchChatData.js

Fix: Ensure Admin role tag visibility for all users in channel messages
Fixes #783 
https://github.com/user-attachments/assets/12ed48da-6f35-4b16-8ef2-4c184fa438f4
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-784 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix: ensure Admin role tag is visible to all users in channel messages

---

packages/react/src/views/ChatHeader/ChatHeader.js

This PR resolves issues where channel information persists in the UI even after a user logs out.
Fixes #850 
[Screencast from 2025-01-09 19-37-19.webm](https://github.com/user-attachments/assets/aa5ffbb8-bacf-4018-8a56-5399eb0c9942)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-851 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: channel info issue after logout

---

packages/react/src/store/messageStore.js

Prevent Quoting the Same Message Multiple Times
Fixes #799 
[fix.webm](https://github.com/user-attachments/assets/c9df2a12-1f69-414e-a0e2-ed7d510cc033)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-800 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Prevent Quoting the Same Message Multiple Times

---

packages/react/src/views/AttachmentHandler/TextAttachment.js
packages/react/src/views/Message/MessageToolbox.js
packages/react/src/views/QuoteMessage/QuoteMessage.js

Fixes #773 
[Screencast from 2025-01-02 22-10-23.webm](https://github.com/user-attachments/assets/9581de58-2d02-4765-98cf-e386a330b319)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-774 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix: quote message window content display and markdown issues

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/views/ChatBody/ChatBody.js
packages/react/src/views/MessageAggregators/common/MessageAggregator.js
packages/react/src/views/MessageList/MessageList.js

This PR Fixes Thread Message Rendering
Fixes #855 
[Screencast from 2025-01-10 02-19-48.webm](https://github.com/user-attachments/assets/277af6ff-ce9b-4459-aa62-a1333ab6acd2)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-860 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix: thread message issue

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/views/MessageAggregators/FileGallery.js
packages/react/src/views/MessageAggregators/common/MessageAggregator.js
packages/ui-elements/src/components/Sidebar/Sidebar.js
packages/ui-elements/src/components/Sidebar/Sidebar.styles.js
packages/ui-elements/src/components/Sidebar/SidebarContent.js
packages/ui-elements/src/components/StaticSelect/StaticSelect.js
packages/ui-elements/src/components/StaticSelect/StaticSelect.styles.js

Implement File Type Filtering Dropdown
Fixes #717 
https://github.com/user-attachments/assets/6062f083-0d97-45f0-af21-108ff46745e0
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-718 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

feat: add file type filtering dropdown to improve file navigation

---

packages/react/src/views/Message/MessageHeader.js

Fix Notification Bugs for Avatar, Room Conversion, and Room Name Change Events.
Fixes #918 

fix:Notification Bugs for Avatar, Room Conversion, and Room Name Change Events.

---

packages/react/src/lib/textFormat.js
packages/react/src/views/ChatInput/ChatInputFormattingToolbar.js

Update Tooltip Names for Formatting Options in ChatInputFormattingToolbar for clarity and to Align with Rocket.Chat.
Fixes #878 
https://github.com/user-attachments/assets/6fa5a9e5-bf0e-4df5-b829-88472713d066

Fix: Tooltips names for Formatting toolbar is not correct and not align with rocket.chat

---

packages/react/src/views/RoomMembers/RoomMemberItem.js
packages/react/src/views/RoomMembers/RoomMembers.styles.js

Fix: Add hover effect to Members section
Fixes #846
https://github.com/user-attachments/assets/c02985cb-80e1-4b7a-8b11-9d96c95af054
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-847 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Add hover effect to Members section

---

packages/react/src/views/Message/MessageToolbox.js

Feat: Show 'Edit Message' Button for all message types 
By 'attachment,' I’m referring to: audio, video, files, and images.
Fixes #825
https://github.com/user-attachments/assets/4887a85f-8743-44bc-8437-91213da4d37c
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-826 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Feat: Show 'Edit Message' Button for all message types

---

packages/react/src/views/AttachmentHandler/AudioAttachment.js
packages/react/src/views/AttachmentHandler/VideoAttachment.js
packages/react/src/views/Message/Message.styles.js
packages/react/src/views/Message/MessageAvatarContainer.js

Fixed responsiveness for attachments and avatar sizes in messages.
Fixes #908 
[Screencast from 2025-01-19 01-16-00.webm](https://github.com/user-attachments/assets/2799e04f-680f-4b28-a223-83bc8b73dd11)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-922 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: attachment and avatar size in messages

---

packages/react/src/views/UserInformation/UserInformation.js

Fix: Capitalize the First Letter of User Roles in User Information Except 'user' Role
Fixes #814
and 
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-815 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Fix: Capitalize the First Letter of User Roles in User Information Except 'user' Role

---

packages/react/src/views/ChatInput/AudioMessageRecorder.js
packages/react/src/views/ChatInput/ChatInputFormattingToolbar.js
packages/react/src/views/ChatInput/VideoMessageRecoder.js

Feat: Add 'Cancel Recording' and 'Finish Recording' tooltips for audio and video recording buttons.
Fixes #811
https://github.com/user-attachments/assets/a94248b9-3e36-47cc-b6a0-7f0c886208ff
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-812 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Feat: Added 'Cancel Recording' and 'Finish Recording' tooltips for audio and video recording buttons.

---

.github/workflows/playwright.yml

Upgrade actions/upload-artifact to v4 to address deprecation
Fixes #916 
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-917 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

fix: upgrade actions/upload-artifact to v4 to address deprecation

---

packages/react/src/lib/formatTimestampGetDate.js
packages/react/src/views/UserInformation/UserInformation.js

Feat: Enhanced 'Email' and 'Created At' Fields of User Info
Fixes #785
https://github.com/user-attachments/assets/1f673d58-e099-40de-87ff-6de07840d93d
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-786 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Feat: Enhanced 'Email' and 'Created At' Fields of User Info

---

packages/react/src/views/AttachmentPreview/AttachmentPreview.js

Feat: Add keyboard shortcuts for closing modal (Escape) and submitting (Enter) in File Upload Window
Fixes #801
https://github.com/user-attachments/assets/23900de0-3b56-43f1-b3d5-bd0253aa73dc
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-802 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Feat: Add keyboard shortcuts for closing modal (Escape) and submitting (Enter) in File Upload Window

---

packages/react/src/views/ChatInput/ChatInput.js

Fixes #806 
[Screencast from 2025-01-05 22-28-38.webm](https://github.com/user-attachments/assets/fe35f755-77f8-4894-9755-949c14e41625)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-807 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

feat: Add keyboard shortcut key for moving starting and ending of the message

---

packages/markups/src/elements/LinkSpan.js
packages/react/src/views/LinkPreview/LinkPreview.js

Added color to the link messages & link present in link preview based on light and dark theme
Fixes #911
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-912 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Added color to the link messages & link present in link preview based on light and dark theme
