src/lib/api.js

- added a regex expression to check whether host is https or HTTP and set use SSL according to that

FIX: when host is https set useSSL as true

---

README.md
src/components/ChatHeader/ChatHeader.js
src/index.js

- More options to be present all the time

[IMPROVE] more options to be present whether or not its fullscreen

---

src/components/ChatBody/ChatBody.js
src/components/ChatHeader/ChatHeader.js
src/components/MessageList/MessageList.js
src/components/MessageList/index.js
src/lib/api.js
src/store/messageStore.js

NEW: Pin and star messages

---

src/components/ChatBody/ChatBody.js
src/components/ChatInput/ChatInput.js
src/components/MessageList/MessageList.js
src/lib/api.js
src/lib/reaction.js
src/store/userStore.js

NEW: react to message

---

src/components/Attachments/Attachment.js
src/components/Attachments/Attachments.js
src/components/Attachments/AudioAttachment.js
src/components/Attachments/ImageAttachment.js
src/components/Attachments/VideoAttachment.js
src/components/Attachments/index.js
src/components/ChatInput/ChatInput.js
src/components/MessageList/MessageList.js
src/lib/api.js

NEW: handling attachments

---

README.md
package-lock.json
package.json
playground/package-lock.json
playground/package.json
playground/src/App.js

- Published v0.0.1 in npm registry here: https://www.npmjs.com/package/embeddedchat

Publishing v0.0.1

---

src/lib/api.js

username's handled as per RC core repo

---

src/components/MessageList/MessageList.js
src/lib/api.js

Add Delete Message Functionality

---

src/components/ChatBody/ChatBody.module.css

I've tried to solve Overflown Message View issue
Fixes # 45

Fix overflow of long messages

---

.eslintrc.json
src/components/ChatHeader/ChatHeader.js
src/components/MessageList/MessageList.js
src/components/RoomMembers/RoomMember.js
src/components/RoomMembers/RoomMember.module.css
src/components/RoomMembers/RoomMemberItem.js
src/components/RoomMembers/UserStatus.js
src/lib/api.js
src/store/index.js
src/store/memberStore.js

As an EmbedChat developer
##I need to:  Add an option for the users to see all the members of that channel
##So That: People know who all are there on the channel
Fixes #38 
[screen-capture.webm](https://user-images.githubusercontent.com/42451210/212967218-a0417a9f-ab91-4379-af6e-41bc04cba326.webm)

Support to see the members of the channel

---

src/components/ChatInput/ChatInput.js
src/components/ChatInput/ChatInput.module.css

This will help users realise that the emoji, add attachments and send message icons are clickable, improving accessibility!

accessibility(cursor): improved accessibility for the emoji picker, add attachments and send message

---

src/components/Attachments/Attachment.js
src/components/Attachments/Attachments.js
src/components/Attachments/AudioAttachment.js
src/components/Attachments/ImageAttachment.js
src/components/Attachments/VideoAttachment.js
src/lib/api.js

On uploading the image it was not visible on chat as an image.
After this PR it will be visible as an image instead of a file
Fixes #96 
Fixes #89
https://user-images.githubusercontent.com/67755128/213980859-c3681d29-f36a-4ef3-91a6-7e9d9f551b6a.mp4

fix:image not display

---

src/components/ChatHeader/ChatHeader.js
src/components/MessageList/MessageList.js
src/components/SearchMessage/SearchMessage.js
src/components/SearchMessage/SearchMessage.module.css
src/lib/api.js
src/store/index.js
src/store/searchMessageStore.js

Fixes #110
https://user-images.githubusercontent.com/76397035/215354834-ab8890fe-9ce6-4f4c-8e5e-5e20fc4851e7.mp4

Added Search Message functionality

---

.github/ISSUE_TEMPLATE/feature.md

Fixed typo of `EmbedChat` to `EmbeddedChat` in issue/feature template

fixed typo in issue/feature template

---

package-lock.json
src/components/Attachments/Attachment.js

fix:changed hardcoded url to RCInstance.getHost() (RocketChat#132)

---

src/components/MessageList/MessageList.js

New pr for Missing key prop in task-6 issue(#132)

---

playground/src/index.css
src/components/ChatBody/ChatBody.js
src/components/ChatBody/ChatBody.module.css
src/components/ChatHeader/ChatHeader.module.css
src/components/MessageList/MessageList.js
src/components/MessageList/MessageList.module.css

Closed the previous pull request since it was not optimised hence creating a new one.
-Fixed the position of ChatBody by changing the width unit.
-Fixed the position of Header clipping by changing the position t absolute.
Fixes #134 ( Fix for the positions of ChatHeader and Message Box )
https://user-images.githubusercontent.com/50259284/221089852-3573c891-a905-4221-8f8f-8c1b9badeb76.mp4

fix-header-clipping

---

playground/src/index.css
src/components/ChatBody/ChatBody.js
src/components/ChatBody/ChatBody.module.css
src/components/ChatHeader/ChatHeader.module.css
src/components/MessageList/MessageList.js
src/components/MessageList/MessageList.module.css

This pull request adds the ability to drag and drop attachments directly into the chat window, making it easier and more intuitive for users to share files with one another.
The following changes have been made to implement this feature:
Added drag and drop event listeners to the chat window.
Implemented logic to handle file uploads when files are dropped into the chat window.
Added a UI component to display the uploaded file in the chat window.
BEFORE:
https://user-images.githubusercontent.com/50259284/221878096-85ef089c-47ba-45c0-83cc-aba4899e43fb.mp4
AFTER:
https://user-images.githubusercontent.com/50259284/221878205-e269e04d-fe38-472b-9fb5-c29a671f3c6b.mp4

[IMPROVE] Drag drop attachments

---

src/components/TotpModal/TwoFactorTotpModal.js

Hi, I removed unused import mentioned in Task 8 of issue #132. The task is small so I don't believe a screenshot is required. Also, task #132 is closed but it has not been completed yet. It might have been closed mistakenly.
Thank you!

Fixed unused import: #132

---

src/components/ChatBody/ChatBody.js
src/components/ChatInput/ChatInput.js
src/components/Markup/elements/InlineElements.js
src/components/Markup/elements/Mention.js
src/components/MessageList/MessageList.js
src/index.js

The app was crashing when the user is not authenticated. 
1. trying to set mentions when the user mention data is not available. As the current implementations search if the user who is mentioned is present in the member list of the room or not. But we don't have that member list information when the user is authenticated.
2. Fetching roles (which requires auth) and calling functions on null/undefined objects.
Fixes #173

[BUGFIX] mentions and roles causing initial app load to crash when unauthed

---

src/components/ChatInput/ChatInput.js
src/components/SearchMessage/SearchMessage.js

The search functionality is now showing the messages with the content.
Fixes #167

Fixed Issue #167

---

package.json
src/components/Attachments/AttachmentWindow.js
src/components/Attachments/AttachmentWindow.module.css
src/components/Attachments/AttachmentWindow/preview/audio.js
src/components/Attachments/AttachmentWindow/preview/default.js
src/components/Attachments/AttachmentWindow/preview/image.js
src/components/Attachments/AttachmentWindow/validateComponent.js
src/components/ChatBody/ChatBody.js
src/components/ChatInput/ChatInput.js
src/index.js
src/lib/api.js
src/store/attachmentwindow.js

This pull request builds the ability to add descriptions and change name to attachments directly into the chat window, making it easier to understand the context with one another.
The following changes have been made to implement this feature:
1. A modal window for modifying the file name and description.
BEFORE:
https://user-images.githubusercontent.com/50259284/222400440-50c53e59-0702-4fae-9bfd-84c3995f13b8.mp4
AFTER:
https://user-images.githubusercontent.com/50259284/222400520-46a0167a-73e4-48a0-a7d0-ec6480f28fc6.mp4

[IMPROVE] Attachment window

---

README.md
playground/src/App.js
src/components/Attachments/AttachmentWindow.js
src/components/ChatBody/ChatBody.js
src/components/ChatHeader/ChatHeader.js
src/components/ChatInput/AudioMessageRecorder.js
src/components/ChatInput/ChatInput.js
src/components/MessageList/MessageList.js
src/components/Thread/ThreadMessageList.js
src/components/Thread/ThreadMessageList.module.css
src/components/Thread/index.js
src/components/ThreadHeader/ThreadHeader.js
src/components/ThreadHeader/ThreadHeader.module.css
src/components/ThreadHeader/index.js
src/index.js
src/lib/api.js
src/lib/messageListHelpers.js
src/store/messageStore.js

Recently we switched to real-time API. This PR will add thread chat support using the current real-time API.
Fixes #35
https://user-images.githubusercontent.com/15830206/223895120-25251f74-64d7-4963-bda2-af35d6129065.mp4

[ADD] Thread Chat support

---

src/components/Markdown/Markdown.css
src/components/Markup/blocks/ParagraphBlock.js
src/components/Markup/elements/Emoji.js
src/components/MessageList/MessageList.js
src/components/MessageList/MessageList.module.css

[FIX] Big Emoji sizes

---

.gitignore
playground/.gitignore
src/components/ChatInput/ChatInput.js
src/lib/emoji.js

Adds the ability to preview emojies in the text-area
BEFORE :
https://user-images.githubusercontent.com/50259284/224507546-4d90c771-d913-4413-8434-993b537e2064.mp4
AFTER:
https://user-images.githubusercontent.com/50259284/224507549-42ac22ca-7483-4d68-84a0-b0f5af162f2b.mp4

[IMPROVE] Emoji input preview

---

.gitignore
package.json
playground/.gitignore
playground/package.json
src/components/RoomInformation/RoomInformation.module.css
src/components/RoomMembers/RoomMember.js
src/components/RoomMembers/RoomMember.module.css
src/components/RoomMembers/inviteMembers/InviteMembers.js
src/components/SearchMessage/SearchMessage.module.css
src/lib/api.js
src/store/inviteStore.js

Adds the ability to create invites for members to be added, just like in the RC core app.
To utilize this feature, users can easily access it by navigating to the options section of the platform, selecting "Members", and clicking the "Invite link" button.
https://user-images.githubusercontent.com/50259284/224479860-f4e9e516-03c7-408b-993d-0e35acb44745.mp4

[FEAT] Invite feature

---

src/components/ChatBody/ChatBody.js
src/components/MessageList/MessageList.js
src/components/Thread/ThreadMessageList.js

App crashes when loading thread messages of starred and pinned messages
Star/pin any thread main message
Open the starred/pinned message
Click on thread inside to view its messages
Fixes #192 
Fix for star/pin thread message
[screen-capture (1).webm](https://user-images.githubusercontent.com/42451210/224569745-c6ed9ea9-b892-4f8a-bd5b-8cf3b3337cea.webm)
Fix for removing thread messages
[screen-capture.webm](https://user-images.githubusercontent.com/42451210/224720393-6850711d-2131-4e0b-a703-87018f2c68b0.webm)

Bugs related to thread messages

---

src/components/ChatHeader/ChatHeader.module.css
src/components/ChatInput/ChatInput.js
src/components/TypingUsers/index.js
src/index.js

Fixes issues caused by #175 
[x] Code refactoring
[x] Lint fixes
[x] fixed codes removed by mistake due to resolving of merge conflicts

[HOTFIX] fixes for pervious merges

---

README.md

Add Contributor Stats Widget

---

src/lib/createPendingMessage.js

This method changes Math.random() with crypto.randomUUID() and crypto.generateRandomValues() for pending message generation. This id generation is helpful when we want to track the sending of messages using API.
There are some known issues with Math.random() https://v8.dev/blog/math-random
Fixes #205

[FIX] replace Math.random() with crypto api.

---

src/components/Message/Message.module.css
src/index.js

This pr fixes:
1. Message list behind chat input #202
2. New lines not preserved while message in pending state. #203
Fixes #202 #203
https://user-images.githubusercontent.com/15830206/225815271-03029359-08eb-469c-b707-409b9f1070c3.mp4

[FIX] Fixes minor UI isses

---

packages/react/src/components/Button/Button.js
packages/react/src/components/Button/Button.stories.js
packages/react/src/components/Button/index.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/components/MessageList/MessageList.js
packages/react/src/components/ReportMessage/ReportWindowButtons.js
packages/react/src/components/RoomMembers/RoomMember.js
packages/react/src/components/SearchMessage/SearchMessage.js
packages/react/src/components/TotpModal/TwoFactorTotpModal.js
packages/react/src/components/auth/LoginForm.js
packages/react/src/theme/DefaultTheme.js

This PR creates new custom button and replaces fuselage's variant of button throughout the codebase.

[NEW] Button replacement for fuselage

---

packages/react/docs/theming.md

This pr includes theming.md where I have explained our theming principles

Adding theming.md

---

packages/react/src/components/RoomInformation/RoomInformation.js

- Commented-  //import { Avatar } from '@rocket.chat/fuselage'; 
- Added  - import { Avatar } from '../Avatar/Avatar'
Fix #240

Fix Avatar Issue #240

---

packages/react/.eslintrc.json
packages/react/package.json
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/Menu/Menu.js
packages/react/src/components/Menu/Menu.stories.js
packages/react/src/components/Menu/MenuItem.js
packages/react/src/components/Menu/index.js
packages/react/src/theme/useComponentOverrides.js

This PR adds our own menu component. The component supports our current theming implementation.
Fixes #235

new menu component

---

packages/react/src/components/CheckBox/CheckBox.js
packages/react/src/components/CheckBox/CheckBox.stories.js
packages/react/src/components/CheckBox/index.js
packages/react/src/components/Markup/blocks/TaskListBlock.js

This PR includes a custom checkbox component with theming support
Fixes #239

added custom checkbox

---

packages/react/src/components/RoomMembers/RoomMemberItem.js
yarn.lock

#Fixed the broken structure of the member list

memberlistFix-1  

---

packages/react/src/components/SearchMessage/SearchMessage.js
yarn.lock

Vertically centered the Enter button in Search Messages.
Fixes #271

fix/#271 - Fixed the enter button misalignment in search messages

---

packages/react/src/components/Message/Message.js
packages/react/src/components/Message/MessageHeader.js

fix: added star icon to message header 

---

packages/react/src/components/ChatBody/ChatBody.js

#Styled scrollbar for message list 
Made use of webkit-scrollbar to style the scrollbar, these changes will successfully change the scrollbar on all webkit-based browsers (e.g., Chrome, Edge, Opera, Safari, all browsers on iOS).
Appearance after changes on MS Edge:
Appearance after changes on Google Chrome:
Fixes #284

Styled scrollbar for messagelist

---

packages/react/src/components/Message/MessageHeader.js

This PR will fix the error caused by the null reference in the MessageHeader component.

hotfix: fix null reference error

---

packages/react/src/components/Markup/blocks/ParagraphBlock.js
packages/react/src/components/Message/Message.js
packages/react/src/components/Message/MessageAvatarContainer.js
packages/react/src/components/Message/MessageBody.js
packages/react/src/components/Message/MessageBodyContainer.js
packages/react/src/components/Message/MessageContainer.js
packages/react/src/components/Message/MessageHeader.js

This PR fixes few UI issues with the message list
1. Message Divider appeared incorrectly for nonsequential messages
2. Message Avatar incorrect sizes
3. Abnormal spacing between paragraph blocks
4. Star not appearing for starred messages.

fix: message list ui bug fixes

---

packages/react/src/components/Markup/blocks/ParagraphBlock.js
packages/react/src/components/Message/Message.js
packages/react/src/components/Message/MessageAvatarContainer.js
packages/react/src/components/Message/MessageBody.js
packages/react/src/components/Message/MessageBodyContainer.js
packages/react/src/components/Message/MessageContainer.js
packages/react/src/components/Message/MessageHeader.js
packages/react/src/components/RoomInformation/RoomInformation.js

This PR removes fuselage from room information component

Roominformation: remove fuselage

---

packages/react/src/components/SearchMessage/SearchMessage.js

This PR fixes bugs related to SearchMessage feature.

fix search message

---

packages/auth/src/RocketChatAuth.ts

This PR fixes incorrect auth error type in RocketChatAuth which caused build to fail.

fix auth api error type

---

packages/react/src/components/uiKit/elements/ImageElement.styles.js

This PR removes the dependencies of @rocketchat/styles as we are using emotion.sh for our styling.

fix ImageElement.styles.js

---

packages/rc-app/EmbeddedChatApp.ts
packages/rc-app/endpoints/InfoEndpoint.ts
packages/rc-app/lib/getAllowedOrigins.ts
packages/rc-app/lib/isAllowedOrigin.ts
packages/rc-app/settings/settings.ts

Introduces the InfoEndpoint to RC Apps, providing essential configuration details and the status of configured items.
Added: InfoEndpoint.
Functionality: Returns configuration data and status of key items.
```
{
"config": {
"serviceName": "embeddedchat",
"client_id": "SffmRfhsvtYQg7YAM",
"allowedOrigins": [],
"redirect_uri": "http://localhost:3000/api/apps/public/4c977b2e-eda2-4627-8bfe-2d0358304a79/callback"
},
"configuredItems": {
"client_id": true,
"client_secret": true,
"custom_oauth_name": true
}
}
```
Enhances service configuration visibility.
Aids in debugging and validation.
Facilitates API integration.

added info endpoint to rc-apps

---

packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/context/RCInstance.js
packages/react/src/index.js

This PR introduces a series of general code improvements across the project, aimed at enhancing readability, performance, and maintainability.
- Refactored various functions for better clarity and efficiency.
- These changes are expected to improve the overall code quality and ease future development efforts.
- No new features are introduced, and existing functionality remains unaffected.
Feedback and suggestions are welcomed to further refine the codebase.

general code improvements

---

README.md
packages/react/README.md

This PR presents a comprehensive update to the `EmbeddedChat` documentation. The update not only enriches the content with detailed usage instructions and development setup but also incorporates relative linking for improved navigability.
1. **Enhanced EmbeddedChat Documentation**:
- Expanded the sections on installation, basic usage, and prop explanations.
- Detailed the three authentication modes (`TOKEN`, `PASSWORD`, `OAUTH`) with examples.
- Added guidelines for theming, customization, and handling the closable state.
2. **Development Environment Setup**:
- Provided a step-by-step guide for setting up the local development environment.
- Included instructions for using Storybook, managing dependencies, and running the `auth` and `api` packages in development mode.
3. **Local Setup and …

Comprehensive Documentation Update for EmbeddedChat

---

packages/react/package.json
packages/react/rollup.config.js
yarn.lock

minor build fix

---

packages/htmlembed/package.json
yarn.lock

Updating the version of @embeddedchat/react in htmlembed project

ec react version bump

---

packages/api/CHANGELOG.md
packages/api/package.json
packages/api/src/EmbeddedChatApi.ts
packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/ChatInput/ChatInputFormattingToolbar.js
packages/react/src/components/EmbeddedChat.js
packages/react/src/components/EmbeddedChat.styles.js
packages/react/src/components/Message/MessageReactions.js
yarn.lock

This pull request introduces several key fixes to improve the functionality and user experience. The following items have been addressed:
- **Token Handling for SSR:** Implemented new utilities for token handling that are compatible with Server-Side Rendering, ensuring smoother authentication and session management.
- **Emoji Picker Functionality:** Resolved an issue where the emoji picker in the toolbar was not behaving as expected. It now operates smoothly and integrates well with the message input.
- **Message Reactions Display:** Fixed the sizing of message reactions, making them more consistent and visually appealing across different devices and screen sizes.
- **Menu Options Cleanup:** Removed unused menu options to streamline the user interface, enhancing overall usability and …

Fixes for Token Handling, Emoji Picker, Reactions, and UI Cleanup

---

.changeset/big-stingrays-sparkle.md
packages/htmlembed/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/store/messageStore.js

This PR fixes the issue which cause app to crash while send thread messages

Fix: Break on sending thread message

---

.changeset/late-mirrors-melt.md
packages/htmlembed/CHANGELOG.md
packages/htmlembed/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/components/ChatInput/ChatInput.module.css
packages/react/src/components/Message/Message.js
packages/react/src/components/Message/MessageToolbox.js

This PR fixes and further improves the message editing feature.
1. Fix the bugs related to message editing
2. Adds an effect to message which is currently being edited
3. Other UX improvements

Improved: message editing feature

---

packages/react/src/components/ChatInput/ChatInputFormattingToolbar.js
packages/react/src/components/Message/Message.js
yarn.lock

fixed bug of failed to change emoji description into emoji itself

---

packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/components/EmbeddedChat.js

The issue of the focus not transferring to new-message is fixed.
Fixes #166 
[scroll.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/96504d3f-38ac-4aaf-926f-b98daa98b3b8)

Fix/#166 scroll (focus) to new message

---

packages/react/src/components/ChatInput/ChatInput.js

This PR fixes the issue mentioned in #365 .
Fixes #365 
[type2.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/4d95ae12-0b42-4fb2-bfeb-b2da3ad7784e)

Typing-text fixed

---

packages/react/src/components/auth/LoginForm.js
packages/react/src/components/auth/icons/EyeClose.js
packages/react/src/components/auth/icons/EyeOpen.js

I added the eye icon (closed and open) to toggle between password visibility and added logic to ensure proper functioning!
Fixes #369

Add toggle password visibility

---

packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/Message/MessageMetrics.js
packages/react/src/components/uiKit/elements/ButtonElement.js

Resolved warning 3.
Addresses #361 
[warn1.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/ba9b04a7-d35b-434f-9aa8-0236b9be72d3)

Warning 3 Resolved

---

packages/react/src/components/ChatInput/ChatInputFormattingToolbar.js

Resolved Warning 4
Addresses #361

Warning 4 Resolved

---

packages/react/src/components/ChatInput/ChatInputFormattingToolbar.js

Fixed the emoji picker issue mentioned in #446 issue
Fixes #446 
https://github.com/RocketChat/EmbeddedChat/assets/125182653/c21a55ae-ef5b-4ea9-83f9-db6dca867d2a

fix: emoji_picker

---

packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/components/CheckBox/CheckBox.js
packages/react/src/components/EmbeddedChat.js
packages/react/src/components/Message/Message.js
packages/react/src/components/Modal/Modal.js
packages/react/src/components/Modal/ModalBackdrop.js
packages/react/src/components/Tooltip/Tooltip.js
packages/react/src/components/uiKit/blocks/UiKitModal.js

fix: linting issues

---

packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/components/ChatBody/RecentMessageButton.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/components/CommandList/CommandsList.js
packages/react/src/components/DynamicHeader/DynamicHeader.js
packages/react/src/components/EmbeddedChat.js
packages/react/src/components/LinkPreview/LinkPreview.js
packages/react/src/components/Markup/elements/LinkSpan.js
packages/react/src/components/Mentions/MembersList.js

This is just a small PR to fix some of the minor bugs i could see in the console and in appearance
Fixes # NA
I am not creating an issue for this as it is not a very significant PR, it just fixes some of console errors, button appearance and some linting warnings and unnecessary renders.
Attaching some screenshots of issues which i tried fixing here:

chore: minor bugs

---

README.md

Documentation to enable CORS added.

add documentation to enable CORS

---

packages/react/src/components/ChatInput/ChatInput.js

Fixed message sending issue using the send-btn. The send-btn was opening long Message modal instead of sending message
Fixes NA

chore: fixed message send issue using send-btn

---

packages/react/src/components/Attachments/AttachmentWindow.js
packages/react/src/components/Attachments/AttachmentWindow.module.css
packages/react/src/store/attachmentwindow.js

Added sending state to file upload modal
Fixes #521 
https://github.com/RocketChat/EmbeddedChat/assets/29705333/00303d92-b4cf-4679-9e9a-718b0d730d81

[Feat/fix] Added sending state to file upload modal

---

packages/react/src/components/PinnedMessages/PinnedMessages.js
packages/react/src/components/StarredMessages/StarredMessages.js
packages/react/src/components/UserMentions/UserMentions.js

This PR adds real-time updates for pinned, starred, and mentioned messages in the sidebar by utilizing messages directly as messages are updated in realtime, rather than explicitly fetching them from APIs.
Fixes #543 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/0e8580ce-d018-4fbb-a501-858738dde9d7

feat: realtime sidebars

---

packages/react/src/components/ChatInput/ChatInput.js

Parse breaklines when editing multi-line message. Fixed the JSON parsing error.
Closes #550

fix: parse breaklines when editing multi-line message

---

packages/react/src/components/ChatHeader/ChatHeader.js
packages/react/src/components/ChatInfo/ChatInfo.js
packages/react/src/components/ChatInput/ChatInput.js
packages/react/src/components/TypingUsers/index.js
packages/react/src/store/channelStore.js

Fixes #555
https://github.com/RocketChat/EmbeddedChat/assets/78961432/86bc33e6-8fa1-4cce-8952-48eb8b4b1fd0

feat: Addition of chatinfo to display status

---

packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/components/MessageList/MessageList.js

This PR logically places the sidebar in its appropriate position and resolves the issue of not opening the sidebars when there are no messages in the channel.
Fixes #558
https://github.com/RocketChat/EmbeddedChat/assets/78961432/05a63068-ecef-4baa-8767-daa497007a4a

fix: sidebar can't open when no messages in the channel

---

packages/react/src/components/ChatInput/ChatInput.js

Fix for Editing Attachment Descriptions
Fixes #553 
https://github.com/RocketChat/EmbeddedChat/assets/78961432/a51a5349-4554-4c8b-9a24-45e3a4c02b88

fix: edit attachment description

---

packages/react/src/components/Message/MessageHeader.js

This PR fixes the issue where notifications are not displayed correctly whenever some event happens in the channel
Fixes N.A.
Before:
After:

fix: display notification when event happens

---

packages/api/src/EmbeddedChatApi.ts
packages/react/src/components/Avatar/Avatar.js
packages/react/src/components/ChatBody/ChatBody.js
packages/react/src/components/Message/MessageAvatarContainer.js
packages/react/src/components/UserInformation/UserInformation.js
packages/react/src/lib/formatTimestamp.js
packages/react/src/store/userStore.js

This PR integrates the feature to display the information of a user on clicking the avatar.
Fixes #571 
[userInfo.webm](https://github.com/RocketChat/EmbeddedChat/assets/95426993/acdc4dd0-6068-4091-b14b-a3f23385f143)
*This PR will require a re-build of the api package using -> `yarn build` under  `/packages/api` *

User info display

---

packages/api/src/EmbeddedChatApi.ts
packages/auth/src/IRocketChatAuthOptions.ts
packages/auth/src/RocketChatAuth.ts
packages/auth/src/auth.ts
packages/react-native/src/components/EmbeddedChat.js
packages/react/src/hooks/useRCAuth.js
packages/react/src/store/index.js
packages/react/src/store/loginStore.js
packages/react/src/store/loginmodalStore.js
packages/react/src/store/messageStore.js
packages/react/src/uiKit/blocks/SectionBlock.js
packages/react/src/views/ChatBody/ChatBody.js
packages/react/src/views/ChatInput/ChatInput.js
packages/react/src/views/EmbeddedChat.js
packages/react/src/views/LoginForm/LoginForm.js
packages/react/src/views/MessageList/MessageList.js

In this PR, I have restructured the way auto-login works. Previously, it was implemented within the `EmbeddedChat` component, directly interacting with the authentication package and managing state. Now, I have moved this functionality to `EmbeddedChatAPI`. This change allows `EmbeddedChat` to interact with `EmbeddedChatAPI` to handle auto-logins more effectively as side effects. This restructuring has enabled better management of auto-login states, facilitating the display of throbbers or custom messages during login or while messages are loading.
Fixes: N/A
https://github.com/RocketChat/EmbeddedChat/assets/78961432/69df65ff-4760-4fe8-ba08-756a360ee350

fix/feat: Improve auto login + loading screens

---

packages/rc-app/EmbeddedChatApp.ts
packages/rc-app/lib/isValidCssDimension.ts

Fixes: N/A
https://github.com/RocketChat/EmbeddedChat/assets/78961432/2eaa4e50-ad38-4ac8-8cc7-d8eebd875f26

feat: added basic css dimension validation in RC app

---

packages/react/src/views/AttachmentPreview/AttachmentPreview.js

Fixes #623 
[Screencast from 16-09-24 06:05:40 PM IST.webm](https://github.com/user-attachments/assets/21143a24-350f-4bc9-b0a3-961977eb8cc5)

Fix: emoji parsing issue in file description

---

packages/react/src/views/MessageAggregators/common/MessageAggregator.js

Starred Message in thread is shown in starred Modal as well.
Fixes #627
https://github.com/user-attachments/assets/c4288356-0bab-485e-a5d9-d07f55adedf8

Starred Model fix

---

.github/workflows/build-and-lint.yml
.github/workflows/deploy.yml

Modified deployed workflow such that now it will build the packages of monorepo combinely rather than seprate building

Combine build steps for react, ui-elements, and layout_editor packages

---

packages/react/src/views/ChatInput/ChatInput.js
packages/react/src/views/QuoteMessage/QuoteMessage.styles.js

Added max-width for the container and wrapped the text content
Fixes #658 
[after_fix.webm](https://github.com/user-attachments/assets/b89099a8-5293-4d03-8fb7-e95d609924c3)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-659 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Prevent Quote Message Overflow

---

packages/react/src/store/messageStore.js
packages/react/src/views/AttachmentHandler/Attachment.js
packages/react/src/views/AttachmentHandler/AttachmentMetadata.js
packages/react/src/views/AttachmentHandler/AudioAttachment.js
packages/react/src/views/AttachmentHandler/ImageAttachment.js
packages/react/src/views/AttachmentHandler/TextAttachment.js
packages/react/src/views/AttachmentHandler/VideoAttachment.js
packages/react/src/views/ChatInput/ChatInput.js
packages/react/src/views/ChatInput/ChatInput.styles.js
packages/react/src/views/Message/BubbleVariant/Bubble.styles.js
packages/react/src/views/Message/Message.js
packages/react/src/views/QuoteMessage/QuoteMessage.js

Fixes #640 
[Screencast from 04-11-24 10:14:00 PM IST.webm](https://github.com/user-attachments/assets/3b9ef13b-e3dd-4b4d-a873-7ca38ed90fac)
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-641/ after approval.

Fix: Quoting issues

---

.github/workflows/build-pr.yml
.github/workflows/deploy-pr.yml

Reverts RocketChat/EmbeddedChat#660
- Reverting due to security issue and inconsistent behaviour

Revert "Added a validation check for pr approval in the deploy-pr workflow"

---

packages/react/src/views/MessageAggregators/common/MessageAggregator.js

Fixes # (issue)
closes #747 
[Screencast from 2024-12-28 23-54-40.webm](https://github.com/user-attachments/assets/6f9d145c-8dc2-4a5e-ab17-43957b2f711a)

fix: jump to message highlights the element 

---

packages/react/src/views/GlobalStyles.js

Feat: Thumb cursor on scrollbar hover
Fixes #834
https://github.com/user-attachments/assets/c593b7a7-4b5a-4e80-8bab-3197d5e48ae6
**Note**: The PR will be ready for live testing at https://rocketchat.github.io/EmbeddedChat/pulls/pr-835 after approval. Contributors are requested to replace `<pr_number>` with the actual PR number.

Feat: Thumb cursor on scrollbar hover

---

packages/react/src/views/ChatInput/ChatInput.js

Fix: Add channel-name in msgBox

---

packages/react/src/views/ChatInput/ChatInput.js

Fixes #837 
[Screencast from 2025-01-08 22-16-10.webm](https://github.com/user-attachments/assets/75fbc366-5f0c-4b49-aab0-e303fcc08972)

fix: handleNewLine function to properly add new line in desired location

---

packages/docs/docs/Usage/embeddedchat_setup.md

Added an important instruction for those who are integrating EmbeddedChat on a vite project

Updated embeddedchat_setup.md
